// Run of Show minuto a minuto (versión 180'). Fuente única para el XLSX y el PDF del entregable 04.
// Numeración de láminas = deck de 180 min (56 láminas; ocultas: 18–19, 49, 53, 56). Post Gates 2 y 3.
// Columnas: inicio, fin, acto, segmento, qué ocurre, A, B, CXO, láminas, materiales, arco, alerta
module.exports = [
  ['-0:60', '-0:15', 'Previo', 'Montaje', 'Mesas en pods (4 × 6); Muro en pared o 2 paneles (≥ 6 m) con 4 pósters grises + póster de revelación enrollado; rotafolios "Lo que escuchamos" y estacionamiento; workbooks cerrados en lugares; sobres del pre-work guardados con B (no en mesas); video local con subtítulos incrustados; QR probado en la red del recinto; temporizador visible', 'Chequeo técnico, deck 180 y video', 'Materiales por mesa (lista maestra), Muro, sobres', '—', '—', 'Checklist de montaje', '—', 'Checklist completo a T–15'],
  ['-0:20', '-0:15', 'Previo', 'Llegada de la CXO', '5 minutos privados con A: su apertura de 2 min, la regla de sala y su compromiso de cierre', 'Conversa con la CXO', 'Recibe participantes', 'Llega 20 min antes', '1', '—', '—', 'Sin anticipar conclusiones'],
  ['0:00', '0:02', 'Apertura', 'Palabras de la CXO', 'La CXO explica en 2 minutos por qué esta conversación importa al negocio y que participará como una directora más', 'Presenta a la CXO en una línea', 'Observa energía de la sala', 'Habla 2 minutos; no presenta el contenido', '1', '—', 'Curiosidad', 'Empezar a la hora aunque falten personas'],
  ['0:02', '0:06', 'Apertura', 'La frase de pasillo y el mapa', '"¿Qué les pasa a estas nuevas generaciones?" y la promesa de otra pregunta al final; mapa de la sesión y lo que cada director se lleva', 'Lidera', 'Abre los workbooks', 'Participa', '2–3', 'Workbook', 'Curiosidad', 'No usar "hoy vamos a aprender"'],
  ['0:06', '0:08', 'Apertura', 'Acuerdos de conversación', 'Tres acuerdos: se usa, no se atribuye (D-13); se vale disentir, también de los datos y de los facilitadores; "puedo pasar". Teléfonos boca abajo. La CXO confirma el acuerdo en una frase', 'Introduce', 'Confirma con la sala', 'Confirma el acuerdo', '4', '—', 'Curiosidad', '—'],
  ['0:08', '0:10', '1 · El espejo', 'Instrucción del Diagnóstico', 'Guion obligatorio: no es una prueba, no mide personalidad ni tiene relación con la edad; primera reacción, no la ideal; incomodidad 1–4', 'Observa', 'Lidera', 'Responde como participante', '5', 'Workbook pp. 3–6', 'Curiosidad', '—'],
  ['0:10', '0:18', '1 · El espejo', 'Respuesta individual', 'Silencio; cada participante responde las 10 situaciones', 'Observa ritmo', 'Tiempo; aviso a los 6 min', 'Responde', '5', 'Workbook, pluma', 'Curiosidad', 'Llegadas tarde: solo situaciones 1–5'],
  ['0:18', '0:21', '1 · El espejo', 'Autopuntuación', 'Hoja de puntuación; respuesta por defecto, rango y detonadores', 'Apoya dudas', 'Lidera', 'Participa', '6', 'Workbook p. 7', 'Curiosidad', 'Sin conteos de sala ni manos por estilo (D-16)'],
  ['0:21', '0:26', '1 · El espejo', 'Conversación en pares', '¿Qué me sorprendió? ¿Qué situación me activó y por qué?', 'Recorre mesas', 'Recorre mesas', 'Participa (par sin reportes directos)', '7', '—', 'Curiosidad', '—'],
  ['0:26', '0:28', '1 · El espejo', 'Plenaria breve e Idea 1', 'Una pregunta, 2–3 voces: "¿Qué significa para ustedes compromiso? ¿Y para la persona más nueva de su equipo?"; A cierra la Idea 1', 'Cierra con Idea 1', 'Aporta una observación de sala', 'No habla primero', '7', '—', 'Curiosidad', 'Handoff B → A con una observación'],
  ['0:28', '0:29', '2 · La provocación', 'Encuadre del video', 'A: "Es una opinión popular; algunas cosas les van a resonar y otras no tienen respaldo. No se los vamos a explicar."', 'Lidera', 'Prepara video', 'Participa', '8', '—', 'Incomodidad', 'No explicar el video'],
  ['0:29', '0:34', '2 · La provocación', 'Fragmento de Simon Sinek', 'Proyección del fragmento congelado en T–14 (≤ 5 min)', 'Observa reacciones', 'Opera video', 'Observa', '8', 'Video local', 'Incomodidad', 'Subtítulos incrustados; respaldo en laptop 2'],
  ['0:34', '0:40', '2 · La provocación', 'Cuatro preguntas en mesa', '¿Con qué estuvieron de acuerdo? ¿Qué los incomodó? ¿Qué creen que no ve? ¿Qué cambió: la gente o el trato?', 'Recorre mesas', 'Recorre mesas', 'Participa', '9', 'Tarjeta de mesa con las 4 preguntas', 'Incomodidad', 'Facilitadores neutrales'],
  ['0:40', '0:43', '2 · La provocación', 'Captura visible', 'Una frase por mesa al rotafolio; pregunta de seguimiento: "¿Qué de lo que dice aplica a cualquier persona, de cualquier edad?"', 'Agradece; anuncia que se retoma en el Acto 5', 'Escribe textual', 'Participa', '9', 'Rotafolio "Lo que escuchamos"', 'Incomodidad', 'No debatir con Sinek'],
  ['0:43', '0:47', '3 · El Muro', 'Colocar tarjetas en silencio', 'Cada persona coloca 3 tarjetas (16 por mesa, en primera persona) en la generación a la que la atribuiría; dos oleadas de 90 s', 'Observa dudas', 'Lidera', 'Participa', '10', '64 tarjetas + 16 repuesto, cinta azul', 'Incomodidad', '"¿Y si aplica a todas?": "donde la verías primero"'],
  ['0:47', '0:50', '3 · El Muro', 'Recorrer el muro', 'Observar dónde se amontonan tarjetas y qué frase aparece en varias zonas; la sala queda en semicírculo', 'Anota observaciones', 'Cuida el tiempo; invita al semicírculo', 'Participa', '10', '—', 'Incomodidad', 'No fotografiar el Muro (D-14)'],
  ['0:50', '0:57', '3 · El Muro', 'Revelación en 3 pasos', '1) ¿Qué ven? 2) "¿Quién en esta sala se reconoce en esta frase?" (mano alzada) 3) "¿Estamos describiendo generaciones o seres humanos?"; las tarjetas salen de las zonas al póster NECESIDADES HUMANAS', 'Lee en voz alta; frase de salida', 'Lidera; mueve tarjetas', 'Participa', '11–12', 'Póster de revelación', 'Incomodidad → Reconocimiento', 'Nunca atribuir tarjetas a personas o mesas'],
  ['0:57', '0:58', '4 · Mito vs. Dato', 'Instrucción', 'Tres tarjetas de voto; voto simultáneo al contar tres', 'Lidera', 'Reparte tarjetas', 'Vota como todos', '13', '3 tarjetas por persona', 'Reconocimiento', '—'],
  ['0:58', '1:08', '4 · Mito vs. Dato', 'Cinco afirmaciones', 'Por afirmación (≈2 min): lectura, voto, distribución, una voz disidente, revelación', 'Lidera', 'Anuncia la distribución (no se registra)', 'Vota; no se le pregunta', '14–25 (18–19 ocultas)', '—', 'Reconocimiento', 'Corte: si a la 1:05 no inicia la 4, resumirla; la 5 (del video) es obligatoria'],
  ['1:08', '1:10', '4 · Mito vs. Dato', 'Una creencia revisada · Idea 2', '1 min de escritura: "una creencia que traía hoy y que ahora revisaría"; A explica edad, época y cohorte (≈45 s)', 'Lidera', 'Anuncia receso', 'Escribe', '26', 'Workbook p. 9', 'Reconocimiento', 'No decir "las generaciones no existen"'],
  ['1:10', '1:20', 'Receso', 'Receso', 'Café fuera de sala; los facilitadores escuchan sin intervenir', 'Recoge frases para el Acto 5', 'Reacomoda sala; voltea paneles del Muro si hace falta', 'Libre', '27', '—', '—', 'Reiniciar a la hora con quien esté'],
  ['1:20', '1:28', '5 · Contextos', 'Cuatro contextos de entrada al trabajo', 'Portadilla (30 s) + cuatro contextos (≈1:20 c/u, tres hitos y "no suponer") + 2 min en pares: ¿a qué mundo entré y qué me enseñó sobre la lealtad? ¿Y mi persona más nueva?', 'Lidera', 'Toma el tiempo de los pares', 'Participa', '28–32', 'Workbook p. 10', 'Reconocimiento', 'Esto describe el entorno, no a las personas'],
  ['1:28', '1:31', '5 · El contrato', 'El contrato cambió', 'Contrato anterior vs. contemporáneo; Fundidora 1986, SICARTSA 1991, ArcelorMittal 2006; "¿qué frase del rotafolio leerían hoy distinto?"', 'Lidera', 'Lee dos frases del rotafolio', 'Participa', '33', 'Rotafolio del Acto 2', 'Comprensión', 'No convertirlo en crítica a la empresa'],
  ['1:31', '1:34', '5 · La lealtad', 'La lealtad se gana, en ambas direcciones', '"¿Por qué esperamos una relación que algunas empresas dejaron de garantizar? ¿Qué depende de mí?"', 'Lidera', 'Observa', 'Participa', '34', '—', 'Comprensión', '—'],
  ['1:34', '1:38', '6 · Motivadores', 'Necesidades comunes y diferencias', 'Lo que casi todos quieren (2 min) · diferencias de frecuencia, forma y urgencia (2 min)', 'Lidera', 'Prepara pregunta', 'Participa', '35–36', 'Workbook p. 11', 'Comprensión', '—'],
  ['1:38', '1:44', '6 · Motivadores', 'El jefe como palanca', 'Dos datos de Gallup (30 s) · 90 s de escritura: la necesidad común que peor atiendo y con quién · 4 min en mesa', 'Enuncia datos', 'Lidera escritura y mesa', 'Participa', '37', 'Workbook p. 11', 'Comprensión', 'Handoff A → B'],
  ['1:44', '1:49', '7 · Espejo del líder', 'Silencio', 'Seis preguntas; 5 minutos de silencio; iniciales de "mi persona"', 'Silencio', 'Lidera; no llena el silencio', 'Reflexiona', '38', 'Workbook p. 12', 'Comprensión', 'Nunca se recorta'],
  ['1:49', '1:54', '7 · Espejo del líder', 'Pares con escucha', 'Uno habla, otro escucha sin aconsejar; cambian; "lo que te escuché decir es…"', 'Recorre', 'Tiempo', 'Participa (trío si hace falta)', '39', '—', 'Comprensión', '—'],
  ['1:54', '1:57', '8 · Laboratorio', 'Lectura del caso', 'Un caso por mesa (4 mesas: A, B, D, E; 5 mesas: + C); subrayar la frase que molesta', 'Observa', 'Lidera', 'Participa', '40', 'Tarjetas de caso', 'Práctica', '—'],
  ['1:57', '2:09', '8 · Laboratorio', 'Trabajo en mesa', 'Seis preguntas sobre hoja A3; relator rotado (no el de mayor rango)', 'Observa: adaptar vs. conceder; firmeza vs. no escuchar', 'Preguntas de reto por mesa', 'Participa; no es relatora', '41', 'Hojas A3, marcadores', 'Práctica', 'Aviso a los 6 y 10 min'],
  ['2:09', '2:18', '8 · Laboratorio', 'Galería y plenaria', 'Hojas en pared; puntos y "?"; tres preguntas comparativas sobre la pared', 'Anota para Acto 9', 'Lidera', 'Participa', '42', 'Puntos adhesivos', 'Práctica', 'Hablar de la pared, no de las personas'],
  ['2:18', '2:20', '8 · Laboratorio', 'Síntesis', '"Coincidimos en lo que no se negocia; diferimos en el cómo. Ese cómo tiene nombre."', 'Recibe handoff', 'Lidera', 'Participa', '42', '—', 'Práctica', 'Handoff B → A'],
  ['2:20', '2:22', '9 · Liderazgo adaptable', 'Respuesta rígida → respuesta adaptable', 'Contraste de respuestas (no de tipos de líder); en seguridad la respuesta firme es la adaptable', 'Lidera', 'Aporta observaciones de mesas', 'Participa', '43', '—', 'Práctica', '[POR CONFIRMAR] integración Speed Absorbent'],
  ['2:22', '2:27', '9 · Liderazgo adaptable', 'LEER → ADAPTAR → ALINEAR', 'A explica (2 min) · en mesa, releen su caso con los tres verbos (2 min) · dos voces (1 min)', 'Lidera', 'Tiempo', 'Participa', '44', 'Workbook p. 14', 'Práctica', '—'],
  ['2:27', '2:28', '10 · Matriz', 'La herramienta y el ejemplo', 'Adapto el cómo, no el qué; ejemplo de Rogelio', 'Recorre', 'Lidera', 'Participa', '45–46', 'Workbook p. 15', 'Práctica', '—'],
  ['2:28', '2:34', '10 · Matriz', 'Llenado individual', 'Escribir arriba una cosa que no sé de mi persona (LEER); columna de mi persona: 3+ celdas de "adapto" y todas las de "no adapto"', 'Recorre', 'Lidera; aviso a los 4 min', 'Participa', '47', 'Workbook p. 15', 'Práctica', 'Columna "no adapto" nunca vacía'],
  ['2:34', '2:39', '10 · Matriz', 'Validación con un par', 'El par solo hace dos preguntas', 'Recorre', 'Tiempo', 'Participa', '47', '—', 'Práctica', '—'],
  ['2:39', '2:41', '11 · Invertir el lente', 'Formación de parejas', 'Parejas por diferencia de trayectoria autodeclarada: "alguien que empezó a trabajar en otro contexto (otra década, empresa, área o país)". Sin edad, sin fila', 'Ajusta discretamente parejas jefe–colaborador', 'Lidera', 'Pareja o trío sin reportes directos', '48', 'Workbook p. 16', 'Apropiación', 'Nadie habla en nombre de su generación'],
  ['2:41', '2:49', '11 · Invertir el lente', 'Cuatro frases', '3 + 3 minutos; "lo que me llevo es…"; dos voces con la frase 4. B entrega los sobres del pre-work en mano', 'Recibe handoff', 'Lidera; entrega sobres', 'Participa', '48', 'Sobres del pre-work', 'Apropiación', 'Sala homogénea: variante oculta (lámina 49)'],
  ['2:49', '2:51', '12 · Compromiso', 'Regreso al inicio', 'Se abre el sobre: ¿responderían hoy lo mismo? Resultado del diagnóstico: ¿qué respuesta necesito usar más con mi persona?', 'Lidera', 'Apoya', 'Participa', '50', 'Sobre del pre-work', 'Apropiación', 'El sobre no se recoge'],
  ['2:51', '2:55', '12 · Compromiso', 'Compromiso escrito', 'DEJAR / EMPEZAR / MANTENER · Una persona / una conversación en 7 días (semana 1 del Experimento) · lo que no voy a negociar', 'Lidera', 'Recorre: "¿con quién, cuándo, sobre qué?"', 'Escribe su propio compromiso', '51', 'Workbook p. 17', 'Apropiación', 'Nunca se recorta'],
  ['2:55', '2:58', '12 · Compromiso', 'Encuesta y vecino', '2 min de encuesta anónima (QR) · 1 min: "en siete días voy a…" al vecino · mención de la tarjeta del Experimento en el sobre', 'Lidera', 'Verifica QR; encuestas impresas de respaldo', 'Responde', '52', 'QR por mesa', 'Apropiación', 'Encuesta dentro del horario'],
  ['2:58', '2:59', '12 · Compromiso', 'Compromiso de la CXO', 'La CXO comparte su propio compromiso, sin evaluar a la sala', 'Cede la palabra', '—', 'Habla 1 minuto', '52', '—', 'Apropiación', 'No resume el taller'],
  ['2:59', '3:00', '12 · Compromiso', 'La otra pregunta y cierre', 'La pregunta que reemplaza a la frase de pasillo (30 s) · frase ancla y "En una siderúrgica, la seguridad no se adapta. El liderazgo sí." (30 s)', 'Cierra', 'Barrido de sala al final', 'Participa', '54–55', '—', 'Apropiación', 'Sin aplausos ni dinámica final'],
];

// Acordeón de recortes si vamos tarde (acumulables, en este orden) — Gate 3 §6.2
module.exports.acordeon = [
  ['+2 min a las 0:43', 'Plenaria del Acto 1 reducida a una voz', '1 min'],
  ['+3 min a las 0:58', 'Afirmación 4 de Mito vs. Dato resumida en una frase (la 5 es obligatoria)', '1 min 40 s'],
  ['+5 min al regresar del receso', 'Contextos del Acto 5 a 60 s cada uno; pares de 2 min se mantienen', '1 min 20 s'],
  ['+5 min a la 1:38', 'Mesa del Acto 6 de 4 a 2 min (una sola voz)', '2 min'],
  ['+5 min a la 1:54', 'Galería del Laboratorio de 4 a 3 min; plenaria de 5 a 4', '2 min'],
  ['+5 min a las 2:39', 'Acto 11 a 8 min (frases 1 y 4)', '2 min'],
  ['Nunca se recortan', 'El silencio del Acto 7, la columna "no adapto", el compromiso escrito, el minuto de la CXO, la frase ancla y la seguridad', '—'],
];

// Mapa de láminas visibles por versión (deck de 56 láminas)
module.exports.mapa = [
  ['180 min', '51 visibles', 'Ocultas: 18–19 (reserva "ya no quieren trabajar"), 49 (variante Invertir el lente), 53 (Experimento, respaldo), 56 (anexo)'],
  ['120 min', '42 visibles', 'Además: 22–23 (reconocimiento), 27 (receso), 29–32 (contextos), 36 (diferencias), 48 (Invertir el lente). Textos variantes: 8 situaciones, 12 tarjetas, 4 afirmaciones'],
  ['90 min', '35 visibles', 'Además: 7 (Idea 1: A la enuncia), 10–12 (Muro), 28, 37, 39. Lámina 9 con pregunta única; Espejo (38) en 2 min antes del Laboratorio'],
];
